#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#AFDEDC"
bspc config normal_border_color "#91A8A4"


# prevent screen saver (`xset q` for more)
xset s off &
xset s noblank &
xset dpms 0 0 0 &
xset -dpms &
# this last one just resets "cycle" to zero. it doesn't matter much, but it's the cleaner
xset s 0 0 &
# disable beep
xset b off &

